### PR TITLE
fixed typos in documentation

### PR DESCRIPTION
**Pull request by Favour-dgreat**

### CODE REVIEW

**Review by Jesulonimi21 — APPROVED** [review]
Thanks a lot for this😄 
😎.

**Comment by AwolDes** [comment]
@Favour-dgreat it would be great if you joined our Discord: https://discord.io/xBacked 

We have some bounties on Gitcoin at the moment that might interest you.

**Comment by Favour-dgreat** [comment]
> @Favour-dgreat it would be great if you joined our Discord: https://discord.io/xBacked
> 
> We have some bounties on Gitcoin at the moment that might interest you.

I'm interested in this can I get a link to check it out. By the way I've joined the discord community

**Comment by AwolDes** [comment]
@Favour-dgreat this is the bounty: https://gitcoin.co/issue/xbacked-dao/xbacked-sdk/28/100028565

Please send a message in the #technical-chat channel & tag me so I can give you the xDev role!

**Pull request merged**
